name: Dev Tools HW

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm-tests:
    runs-on: ubuntu-latest
    steps:
    # Install dependencies and runs tests
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        
      - name: Run test
        run: npm run test
  
  docker-build-image:
    runs-on: ubuntu-latest
    steps:
    # Build docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
  synk-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Snyk scan on Docker image
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
